### ISSUE TITLE
400 (Bad Request) Error when inserting data to the database

### ISSUE THREAD

**Issue by NtandoRaji** [2551250/workwise#44]
I keep getting a "400 (Bad Request) Error" when having apostrophe in text data like - PROJECT_NAME, DESCRIPTION (for both projects & feedback).

**Comment by 2551250** [comment]
SQL treats apostrophes as a end of string character. I think you need to have two apostrophes to prevent this problem. It's probably easiest to just create a function that adds a second apostrophe after every occurrence and then insert into the database.

**Comment by NtandoRaji** [comment]
Thanks, I'll attempt to resolve the issue
