### ISSUE TITLE
Error with testing when trying to upload delete staff member code

### ISSUE THREAD

**Issue by NtandoRaji** [2551250/workwise#57]
Code has been fine so far but with adding the delete code the codecov doesn't want to run tests. Been pulling from main page and adding code but still giving errors when uploading branch, so must be error with testing and deleting

**Comment by 2551250** [comment]
I think moving getAllStaffData from EmployeeManagement.jsx to backend.js. will fix the problem.

**Comment by NtandoRaji** [comment]
Yeah that fixed the problem. Is there a reason why that was causing it?

**Comment by 2551250** [comment]
I don't know why but the tests don't run if they import anything from a file using React or axios.
